repos:

    - repo: git@github.com:humitos/mirrors-autoflake.git
      rev: v1.3
      hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.3
      hooks:
      - id: seed-isort-config

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
      - id: isort
        additional_dependencies:
        - toml

    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        language_version: python3.8

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml

    - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
      rev: v1.0.0
      hooks:
      - id: rst-linter

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
      - id: flake8
