language: python
os: linux

python:
  - "3.7"
  - "3.8"

addons:
  apt:
    update: true

before_install:
  - sudo apt -y install libgirepository1.0-dev

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install --upgrade pip tox-travis codecov

script: tox