language: python
os: linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install --upgrade pip tox-travis codecov
script: tox